FROM openjdk:17
COPY ./Interview-project /usr/src/app
WORKDIR /usr/src/app

# RUN apk upgrade && apk add \
#         bash \
#         openjdk17 \
#         maven \
#         chromium \
#         chromium-chromedriver \
#         sudo \
#         openssh \
#         poppler-utils \
#         vim \
#         vimdiff

SHELL ["/bin/bash", "-c"]
